"use client";
import { useMemo, useState } from "react";
import { Calculator, Percent, ReceiptText, Coffee, GraduationCap, Clock, FileText, ArrowLeftRight, Shuffle, ListChecks, CalendarClock, Gauge } from "lucide-react";
import ToolLayout from "./ToolLayout";

const input="w-full rounded-2xl border border-[#E7D8C7] bg-white px-4 py-3 text-[#2D241C] outline-none focus:border-[#A7744D] focus:ring-4 focus:ring-[#A7744D]/10";
const card="rounded-3xl border border-[#E7D8C7] bg-[#FFFCF8] p-5 shadow-[0_16px_45px_rgba(91,62,38,.08)] sm:p-8";
const btn="rounded-2xl bg-[#A7744D] px-5 py-3 font-bold text-white transition hover:bg-[#8F603C]";
function Num({label,value,setValue,step="any"}:{label:string,value:string,setValue:(v:string)=>void,step?:string}){return <label className="block"><span className="mb-2 block text-sm font-bold text-[#5F4C3D]">{label}</span><input type="number" step={step} value={value} onChange={e=>setValue(e.target.value)} className={input}/></label>}
function Result({children}:{children:React.ReactNode}){return <div className="mt-6 rounded-2xl bg-[#F3E6D8] p-5 text-center text-xl font-black text-[#2D241C]">{children}</div>}

export function DiscountCalculator(){const[p,setP]=useState("100");const[d,setD]=useState("20");const price=+p||0,disc=+d||0,s=price*disc/100;return <ToolLayout title="Discount Calculator" description="Calculate sale price and savings instantly." icon={Percent}><div className={card}><div className="grid gap-4 sm:grid-cols-2"><Num label="Original price" value={p} setValue={setP}/><Num label="Discount (%)" value={d} setValue={setD}/></div><Result>You save {s.toFixed(2)} · Final price {(price-s).toFixed(2)}</Result></div></ToolLayout>}
export function VatCalculator(){const[a,setA]=useState("100");const[r,setR]=useState("20");const[mode,setMode]=useState("add");const amount=+a||0,rate=+r||0;const tax=mode==="add"?amount*rate/100:amount-(amount/(1+rate/100));const total=mode==="add"?amount+tax:amount-tax;return <ToolLayout title="VAT Calculator" description="Add or remove VAT from any amount." icon={ReceiptText}><div className={card}><div className="mb-4 flex gap-2"><button className={mode==="add"?btn:"rounded-2xl bg-[#F3E6D8] px-5 py-3 font-bold text-[#8B6547]"} onClick={()=>setMode("add")}>Add VAT</button><button className={mode==="remove"?btn:"rounded-2xl bg-[#F3E6D8] px-5 py-3 font-bold text-[#8B6547]"} onClick={()=>setMode("remove")}>Remove VAT</button></div><div className="grid gap-4 sm:grid-cols-2"><Num label="Amount" value={a} setValue={setA}/><Num label="VAT rate (%)" value={r} setValue={setR}/></div><Result>VAT {tax.toFixed(2)} · Result {total.toFixed(2)}</Result></div></ToolLayout>}
export function TipCalculator(){const[b,setB]=useState("50");const[t,setT]=useState("15");const[p,setP]=useState("2");const bill=+b||0,tip=bill*(+t||0)/100,people=Math.max(1,+p||1);return <ToolLayout title="Tip Calculator" description="Split a bill and tip fairly between people." icon={Coffee}><div className={card}><div className="grid gap-4 sm:grid-cols-3"><Num label="Bill amount" value={b} setValue={setB}/><Num label="Tip (%)" value={t} setValue={setT}/><Num label="People" value={p} setValue={setP} step="1"/></div><Result>Total {(bill+tip).toFixed(2)} · Each {((bill+tip)/people).toFixed(2)}</Result></div></ToolLayout>}
export function AttendanceCalculator(){const[h,setH]=useState("40");const[a,setA]=useState("4");const req=Math.max(0,Math.ceil((.75*(+h||0)-((+h||0)-(+a||0)))/.25));const rate=(+h||0)?(((+h||0)-(+a||0))/(+h||0))*100:0;return <ToolLayout title="Attendance Calculator" description="Check your attendance rate and how many classes you need to attend." icon={GraduationCap}><div className={card}><div className="grid gap-4 sm:grid-cols-2"><Num label="Total classes" value={h} setValue={setH} step="1"/><Num label="Classes missed" value={a} setValue={setA} step="1"/></div><Result>Attendance {rate.toFixed(1)}% · Attend {req} more for 75%</Result></div></ToolLayout>}
export function ReadingTimeCalculator(){const[text,setText]=useState("");const words=text.trim()?text.trim().split(/\s+/).length:0;return <ToolLayout title="Reading Time Calculator" description="Estimate reading and speaking time for any text." icon={Clock}><div className={card}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste your text…" className={`${input} min-h-64 resize-y`}/><Result>{words} words · {Math.max(1,Math.ceil(words/225))} min read · {Math.max(1,Math.ceil(words/130))} min speech</Result></div></ToolLayout>}
export function TextDiff(){const[a,setA]=useState("");const[b,setB]=useState("");const out=useMemo(()=>{const la=a.split("\n"),lb=b.split("\n");const n=Math.max(la.length,lb.length);return Array.from({length:n},(_,i)=>la[i]===lb[i]?`  ${la[i]??""}`:`- ${la[i]??""}\n+ ${lb[i]??""}`).join("\n")},[a,b]);return <ToolLayout title="Text Difference Checker" description="Compare two blocks of text line by line." icon={ArrowLeftRight} maxWidth="6xl"><div className={card}><div className="grid gap-4 lg:grid-cols-2"><textarea value={a} onChange={e=>setA(e.target.value)} placeholder="Original text" className={`${input} min-h-56 font-mono`}/><textarea value={b} onChange={e=>setB(e.target.value)} placeholder="Changed text" className={`${input} min-h-56 font-mono`}/></div><pre className="mt-4 max-h-80 overflow-auto rounded-2xl bg-[#2D241C] p-4 text-sm text-[#FFF8EF]">{out||"Differences will appear here."}</pre></div></ToolLayout>}
export function RandomPicker(){const[text,setText]=useState("");const[result,setResult]=useState("");const pick=()=>{const x=text.split(/\n|,/).map(s=>s.trim()).filter(Boolean);setResult(x.length?x[Math.floor(Math.random()*x.length)]:"")};return <ToolLayout title="Random Name Picker" description="Pick a random name, option or topic from a list." icon={Shuffle}><div className={card}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="One item per line or separated by commas" className={`${input} min-h-56`}/><button onClick={pick} className={`${btn} mt-4 w-full sm:w-auto`}>Pick randomly</button>{result&&<Result>{result}</Result>}</div></ToolLayout>}
export function ChecklistMaker(){const[text,setText]=useState("");const items=text.split("\n").map(s=>s.trim()).filter(Boolean);return <ToolLayout title="Printable Checklist Maker" description="Turn a list into a clean checklist for printing or studying." icon={ListChecks}><div className={card}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Enter one task per line" className={`${input} min-h-48`}/><div className="mt-6 rounded-2xl border border-dashed border-[#CDB49C] bg-white p-5">{items.length?items.map((x,i)=><label key={i} className="flex items-start gap-3 border-b border-[#F0E4D8] py-3 last:border-0"><input type="checkbox" className="mt-1 h-5 w-5 accent-[#A7744D]"/><span>{x}</span></label>):<p className="text-[#8B796A]">Your checklist will appear here.</p>}</div><button onClick={()=>window.print()} className={`${btn} mt-4`}>Print checklist</button></div></ToolLayout>}
export function StudyPlanner(){const[subjects,setSubjects]=useState("Math\nAccounting\nEnglish");const[hours,setHours]=useState("6");const list=subjects.split("\n").map(s=>s.trim()).filter(Boolean);const each=list.length?(+hours||0)/list.length:0;return <ToolLayout title="Study Time Planner" description="Split your available study time evenly across subjects." icon={CalendarClock}><div className={card}><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-bold text-[#5F4C3D]">Subjects, one per line</span><textarea value={subjects} onChange={e=>setSubjects(e.target.value)} className={`${input} min-h-40`}/></label><Num label="Total study hours" value={hours} setValue={setHours}/></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{list.map(x=><div key={x} className="rounded-2xl bg-[#F3E6D8] p-4 font-bold text-[#2D241C]">{x}: {each.toFixed(1)} hours</div>)}</div></div></ToolLayout>}
export function PaceCalculator(){const[d,setD]=useState("5");const[m,setM]=useState("30");const pace=(+d||0)?(+m||0)/(+d||1):0;return <ToolLayout title="Running Pace Calculator" description="Calculate pace and average speed from distance and time." icon={Gauge}><div className={card}><div className="grid gap-4 sm:grid-cols-2"><Num label="Distance (km)" value={d} setValue={setD}/><Num label="Time (minutes)" value={m} setValue={setM}/></div><Result>Pace {Math.floor(pace)}:{String(Math.round((pace%1)*60)).padStart(2,"0")} min/km · Speed {((+d||0)/((+m||1)/60)).toFixed(2)} km/h</Result></div></ToolLayout>}
export function AverageCalculator(){const[text,setText]=useState("12, 15, 18");const nums=text.split(/[\s,;]+/).map(Number).filter(Number.isFinite);const avg=nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0;return <ToolLayout title="Average Calculator" description="Find the mean, median, minimum and maximum of a number set." icon={Calculator}><div className={card}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Enter numbers separated by commas" className={`${input} min-h-32`}/><Result>Average {avg.toFixed(2)} · Min {nums.length?Math.min(...nums):0} · Max {nums.length?Math.max(...nums):0}</Result></div></ToolLayout>}
export function DeadlineCalculator(){const[date,setDate]=useState("");const[today]=useState(()=>new Date().setHours(0,0,0,0));const days=date?Math.ceil((new Date(date).getTime()-today)/86400000):0;return <ToolLayout title="Deadline Countdown" description="See exactly how many days remain before an exam or deadline." icon={FileText}><div className={card}><label><span className="mb-2 block text-sm font-bold text-[#5F4C3D]">Deadline date</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className={input}/></label>{date&&<Result>{days>=0?`${days} day${days===1?"":"s"} remaining`:`Passed ${Math.abs(days)} days ago`}</Result>}</div></ToolLayout>}
