"use client";

import { useMemo, useState } from "react";

const panel = "rounded-3xl border border-[#E7D8C7] bg-[#FFFCF8] p-6 shadow-[0_16px_45px_rgba(91,62,38,.08)] sm:p-8";
const input = "w-full rounded-2xl border border-[#E7D8C7] bg-white px-4 py-3 text-[#2D241C] outline-none transition focus:border-[#A7744D] focus:ring-4 focus:ring-[#A7744D]/10";
const area = `${input} min-h-56 resize-y font-mono text-sm leading-6`;
const button = "rounded-2xl bg-[#A7744D] px-5 py-3 font-bold text-white transition hover:bg-[#8F603D] disabled:cursor-not-allowed disabled:opacity-50";
const secondary = "rounded-2xl border border-[#D9C4AE] bg-[#FFF9F2] px-5 py-3 font-bold text-[#8F603D] transition hover:bg-[#F3E6D8]";
const label = "mb-2 block text-sm font-bold text-[#4A3A2E]";

function CopyButton({ value }: { value: string }) {
  const [done, setDone] = useState(false);
  return <button className={secondary} onClick={async () => { await navigator.clipboard.writeText(value); setDone(true); setTimeout(() => setDone(false), 1200); }}>{done ? "Copied" : "Copy"}</button>;
}

export function UrlEncoderTool() {
  const [value, setValue] = useState("");
  const [result, setResult] = useState("");
  return <div className={panel}><label className={label}>Text or URL</label><textarea className={area} value={value} onChange={e=>setValue(e.target.value)} placeholder="Paste text or a URL..."/><div className="mt-5 flex flex-wrap gap-3"><button className={button} onClick={()=>setResult(encodeURIComponent(value))}>Encode</button><button className={secondary} onClick={()=>{try{setResult(decodeURIComponent(value))}catch{setResult("Invalid encoded value")}}}>Decode</button><CopyButton value={result}/></div><label className={`${label} mt-6`}>Result</label><textarea className={area} readOnly value={result}/></div>;
}

export function HtmlEntitiesTool() {
  const [value,setValue]=useState(""); const [result,setResult]=useState("");
  const encode=(s:string)=>s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));
  const decode=(s:string)=>{const el=document.createElement("textarea");el.innerHTML=s;return el.value};
  return <div className={panel}><textarea className={area} value={value} onChange={e=>setValue(e.target.value)} placeholder="Enter HTML or plain text..."/><div className="mt-5 flex flex-wrap gap-3"><button className={button} onClick={()=>setResult(encode(value))}>Encode entities</button><button className={secondary} onClick={()=>setResult(decode(value))}>Decode entities</button><CopyButton value={result}/></div><textarea className={`${area} mt-6`} readOnly value={result}/></div>;
}

export function JwtDecoderTool() {
  const [token,setToken]=useState("");
  const decoded=useMemo(()=>{if(!token.trim())return "";try{const parts=token.split(".");if(parts.length<2)throw new Error();const parse=(p:string)=>JSON.parse(decodeURIComponent(Array.from(atob(p.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(p.length/4)*4,"="))).map(c=>"%"+c.charCodeAt(0).toString(16).padStart(2,"0")).join("")));return JSON.stringify({header:parse(parts[0]),payload:parse(parts[1])},null,2)}catch{return "Invalid JWT. This tool decodes only and does not verify signatures."}},[token]);
  return <div className={panel}><label className={label}>JWT token</label><textarea className={area} value={token} onChange={e=>setToken(e.target.value)} placeholder="eyJhbGciOi..."/><label className={`${label} mt-6`}>Decoded header and payload</label><textarea className={area} readOnly value={decoded}/><div className="mt-4"><CopyButton value={decoded}/></div></div>;
}

export function RegexTesterTool(){
 const [pattern,setPattern]=useState(""); const [flags,setFlags]=useState("g"); const [text,setText]=useState("");
 const output=useMemo(()=>{if(!pattern)return {error:"",matches:[] as string[]};try{const r=new RegExp(pattern,flags);const m=flags.includes("g")?Array.from(text.matchAll(r)).map(x=>x[0]):(text.match(r)?.slice(0,1)??[]);return {error:"",matches:m}}catch(e){return {error:e instanceof Error?e.message:"Invalid expression",matches:[] as string[]}}},[pattern,flags,text]);
 return <div className={panel}><div className="grid gap-4 sm:grid-cols-[1fr_140px]"><div><label className={label}>Pattern</label><input className={input} value={pattern} onChange={e=>setPattern(e.target.value)} placeholder="\\b[A-Z]\\w+"/></div><div><label className={label}>Flags</label><input className={input} value={flags} onChange={e=>setFlags(e.target.value)} placeholder="gim"/></div></div><label className={`${label} mt-5`}>Test text</label><textarea className={area} value={text} onChange={e=>setText(e.target.value)}/><div className="mt-6 rounded-2xl bg-[#F7F0E9] p-5"><p className="font-bold text-[#2D241C]">{output.error?"Error":`${output.matches.length} match${output.matches.length===1?"":"es"}`}</p><pre className="mt-3 whitespace-pre-wrap text-sm text-[#6B5B4D]">{output.error||output.matches.map((m,i)=>`${i+1}. ${m}`).join("\n")||"No matches yet."}</pre></div></div>;
}

function csvParse(text:string){const rows:string[][]=[];let row:string[]=[];let cell="";let quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(v=>v!==""))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(v=>v!==""))rows.push(row);return rows}
export function CsvJsonTool(){
 const [value,setValue]=useState(""); const [result,setResult]=useState("");
 const csvToJson=()=>{try{const rows=csvParse(value);const headers=rows.shift()||[];setResult(JSON.stringify(rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""]))),null,2))}catch{setResult("Invalid CSV")}};
 const jsonToCsv=()=>{try{const arr=JSON.parse(value);if(!Array.isArray(arr)||!arr.length)throw new Error();const headers=Array.from(new Set(arr.flatMap((x:Record<string,unknown>)=>Object.keys(x))));const esc=(v:unknown)=>{const s=String(v??"");return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};setResult([headers.join(","),...arr.map((x:Record<string,unknown>)=>headers.map(h=>esc(x[h])).join(","))].join("\n"))}catch{setResult("Enter a JSON array of objects.")}};
 return <div className={panel}><textarea className={area} value={value} onChange={e=>setValue(e.target.value)} placeholder={'CSV or JSON, for example:\nname,age\nAmr,21'}/><div className="mt-5 flex flex-wrap gap-3"><button className={button} onClick={csvToJson}>CSV to JSON</button><button className={secondary} onClick={jsonToCsv}>JSON to CSV</button><CopyButton value={result}/></div><textarea className={`${area} mt-6`} readOnly value={result}/></div>;
}

export function TimestampTool(){
 const [timestamp,setTimestamp]=useState(()=>Math.floor(Date.now()/1000).toString()); const [date,setDate]=useState(()=>new Date().toISOString().slice(0,16));
 const d=useMemo(()=>{const n=Number(timestamp);if(!Number.isFinite(n))return "Invalid timestamp";return new Date(timestamp.length<=10?n*1000:n).toString()},[timestamp]);
 const t=useMemo(()=>{const ms=new Date(date).getTime();return Number.isNaN(ms)?"Invalid date":`${Math.floor(ms/1000)} seconds\n${ms} milliseconds`},[date]);
 return <div className="grid gap-6 lg:grid-cols-2"><div className={panel}><label className={label}>Unix timestamp</label><input className={input} value={timestamp} onChange={e=>setTimestamp(e.target.value)}/><div className="mt-5 rounded-2xl bg-[#F7F0E9] p-5 text-[#2D241C]">{d}</div></div><div className={panel}><label className={label}>Date and time</label><input type="datetime-local" className={input} value={date} onChange={e=>setDate(e.target.value)}/><pre className="mt-5 whitespace-pre-wrap rounded-2xl bg-[#F7F0E9] p-5 text-[#2D241C]">{t}</pre></div></div>;
}

export function SlugGeneratorTool(){const [value,setValue]=useState("");const slug=value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");return <div className={panel}><label className={label}>Title or phrase</label><input className={input} value={value} onChange={e=>setValue(e.target.value)} placeholder="My Great Blog Post"/><label className={`${label} mt-6`}>URL slug</label><div className="flex gap-3"><input className={input} readOnly value={slug}/><CopyButton value={slug}/></div></div>}

export function TextCleanerTool(){const [value,setValue]=useState("");const clean=(mode:string)=>{let s=value;if(mode==="spaces")s=s.replace(/[ \t]+/g," ").replace(/ *\n */g,"\n").trim();if(mode==="lines")s=s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).join("\n");if(mode==="duplicates")s=Array.from(new Set(s.split(/\r?\n/))).join("\n");if(mode==="punctuation")s=s.replace(/[^\p{L}\p{N}\s]/gu,"");setValue(s)};return <div className={panel}><textarea className={area} value={value} onChange={e=>setValue(e.target.value)} placeholder="Paste messy text..."/><div className="mt-5 flex flex-wrap gap-3"><button className={button} onClick={()=>clean("spaces")}>Fix spaces</button><button className={secondary} onClick={()=>clean("lines")}>Remove empty lines</button><button className={secondary} onClick={()=>clean("duplicates")}>Remove duplicate lines</button><button className={secondary} onClick={()=>clean("punctuation")}>Remove punctuation</button><CopyButton value={value}/></div></div>}

export function LineTools(){const [value,setValue]=useState("");const run=(type:string)=>{let a=value.split(/\r?\n/);if(type==="az")a.sort((x,y)=>x.localeCompare(y));if(type==="za")a.sort((x,y)=>y.localeCompare(x));if(type==="reverse")a.reverse();if(type==="unique")a=Array.from(new Set(a));setValue(a.join("\n"))};return <div className={panel}><textarea className={area} value={value} onChange={e=>setValue(e.target.value)} placeholder="One item per line..."/><div className="mt-5 flex flex-wrap gap-3"><button className={button} onClick={()=>run("az")}>Sort A–Z</button><button className={secondary} onClick={()=>run("za")}>Sort Z–A</button><button className={secondary} onClick={()=>run("reverse")}>Reverse lines</button><button className={secondary} onClick={()=>run("unique")}>Unique only</button><CopyButton value={value}/></div></div>}

export function FindReplaceTool(){const [text,setText]=useState("");const [find,setFind]=useState("");const [replace,setReplace]=useState("");const [caseSensitive,setCaseSensitive]=useState(false);const result=useMemo(()=>{if(!find)return text;const safe=find.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return text.replace(new RegExp(safe,caseSensitive?"g":"gi"),replace)},[text,find,replace,caseSensitive]);return <div className={panel}><div className="grid gap-4 sm:grid-cols-2"><div><label className={label}>Find</label><input className={input} value={find} onChange={e=>setFind(e.target.value)}/></div><div><label className={label}>Replace with</label><input className={input} value={replace} onChange={e=>setReplace(e.target.value)}/></div></div><label className="mt-4 flex items-center gap-2 text-sm font-semibold text-[#4A3A2E]"><input type="checkbox" checked={caseSensitive} onChange={e=>setCaseSensitive(e.target.checked)}/> Case-sensitive</label><textarea className={`${area} mt-5`} value={text} onChange={e=>setText(e.target.value)}/><label className={`${label} mt-6`}>Preview</label><textarea className={area} readOnly value={result}/><div className="mt-4"><CopyButton value={result}/></div></div>}

export function LoremIpsumTool(){const [paras,setParas]=useState(3);const base="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";const result=Array.from({length:paras},(_,i)=>i%2?base.replace("Lorem ipsum","Duis aute irure"):base).join("\n\n");return <div className={panel}><label className={label}>Paragraphs: {paras}</label><input type="range" min="1" max="12" value={paras} onChange={e=>setParas(Number(e.target.value))} className="w-full accent-[#A7744D]"/><textarea className={`${area} mt-6`} readOnly value={result}/><div className="mt-4"><CopyButton value={result}/></div></div>}

export function PasswordStrengthTool(){const [value,setValue]=useState("");const info=useMemo(()=>{let score=0;if(value.length>=8)score++;if(value.length>=12)score++;if(/[a-z]/.test(value)&&/[A-Z]/.test(value))score++;if(/\d/.test(value))score++;if(/[^\w]/.test(value))score++;const labels=["Very weak","Weak","Fair","Strong","Very strong","Excellent"];const suggestions=[];if(value.length<12)suggestions.push("Use at least 12 characters");if(!/[A-Z]/.test(value))suggestions.push("Add uppercase letters");if(!/\d/.test(value))suggestions.push("Add numbers");if(!/[^\w]/.test(value))suggestions.push("Add symbols");return {score,label:labels[score],suggestions}},[value]);return <div className={panel}><label className={label}>Password to test</label><input type="password" className={input} value={value} onChange={e=>setValue(e.target.value)}/><div className="mt-6 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><div key={n} className={`h-3 rounded-full ${n<=info.score?"bg-[#A7744D]":"bg-[#E9DED2]"}`}/>)}</div><h2 className="mt-4 text-2xl font-black text-[#2D241C]">{info.label}</h2><ul className="mt-4 space-y-2 text-[#6B5B4D]">{info.suggestions.length?info.suggestions.map(x=><li key={x}>• {x}</li>):<li>Looks strong. Avoid reusing it elsewhere.</li>}</ul></div>}

export function RandomTokenTool(){const [length,setLength]=useState(32);const [token,setToken]=useState("");const generate=()=>{const bytes=new Uint8Array(Math.ceil(length/2));crypto.getRandomValues(bytes);setToken(Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("").slice(0,length))};return <div className={panel}><label className={label}>Token length: {length}</label><input type="range" min="8" max="128" value={length} onChange={e=>setLength(Number(e.target.value))} className="w-full accent-[#A7744D]"/><div className="mt-6 flex flex-wrap gap-3"><button className={button} onClick={generate}>Generate token</button><CopyButton value={token}/></div><textarea className={`${area} mt-6 min-h-32`} readOnly value={token}/></div>}

export function AgeCalculatorTool(){const [birth,setBirth]=useState("");const result=useMemo(()=>{if(!birth)return null;const b=new Date(birth);const now=new Date();if(Number.isNaN(b.getTime())||b>now)return null;let years=now.getFullYear()-b.getFullYear();let months=now.getMonth()-b.getMonth();let days=now.getDate()-b.getDate();if(days<0){months--;days+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(months<0){years--;months+=12}const totalDays=Math.floor((now.getTime()-b.getTime())/86400000);return {years,months,days,totalDays}},[birth]);return <div className={panel}><label className={label}>Date of birth</label><input type="date" className={input} value={birth} onChange={e=>setBirth(e.target.value)}/>{result&&<div className="mt-6 grid gap-4 sm:grid-cols-4">{[["Years",result.years],["Months",result.months],["Days",result.days],["Total days",result.totalDays]].map(([k,v])=><div key={k} className="rounded-2xl bg-[#F7F0E9] p-5 text-center"><div className="text-3xl font-black text-[#A7744D]">{v}</div><div className="mt-1 text-sm font-bold text-[#6B5B4D]">{k}</div></div>)}</div>}</div>}

export function BmiCalculatorTool(){const [weight,setWeight]=useState(75);const [height,setHeight]=useState(185);const bmi=weight/((height/100)**2);const labelText=bmi<18.5?"Underweight":bmi<25?"Healthy range":bmi<30?"Overweight":"Obesity range";return <div className={panel}><div className="grid gap-5 sm:grid-cols-2"><div><label className={label}>Weight (kg)</label><input type="number" className={input} value={weight} onChange={e=>setWeight(Number(e.target.value))}/></div><div><label className={label}>Height (cm)</label><input type="number" className={input} value={height} onChange={e=>setHeight(Number(e.target.value))}/></div></div><div className="mt-6 rounded-3xl bg-[#F7F0E9] p-8 text-center"><div className="text-5xl font-black text-[#A7744D]">{Number.isFinite(bmi)?bmi.toFixed(1):"—"}</div><div className="mt-2 font-bold text-[#2D241C]">{labelText}</div><p className="mt-3 text-sm text-[#6B5B4D]">BMI is a general screening measure, not a diagnosis.</p></div></div>}

export function LoanCalculatorTool(){const [amount,setAmount]=useState(10000);const [rate,setRate]=useState(5);const [years,setYears]=useState(3);const r=rate/100/12,n=years*12;const payment=r===0?amount/n:amount*r*(1+r)**n/((1+r)**n-1);const total=payment*n;return <div className={panel}><div className="grid gap-4 md:grid-cols-3"><NumberField title="Loan amount" value={amount} set={setAmount}/><NumberField title="Annual interest %" value={rate} set={setRate}/><NumberField title="Years" value={years} set={setYears}/></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><ResultCard title="Monthly payment" value={`$${payment.toFixed(2)}`}/><ResultCard title="Total paid" value={`$${total.toFixed(2)}`}/><ResultCard title="Total interest" value={`$${(total-amount).toFixed(2)}`}/></div></div>}

export function CompoundInterestTool(){const [principal,setPrincipal]=useState(1000);const [rate,setRate]=useState(7);const [years,setYears]=useState(10);const [monthly,setMonthly]=useState(100);const m=rate/100/12,n=years*12;const future=principal*(1+m)**n+(m===0?monthly*n:monthly*((1+m)**n-1)/m);const contributed=principal+monthly*n;return <div className={panel}><div className="grid gap-4 md:grid-cols-4"><NumberField title="Starting amount" value={principal} set={setPrincipal}/><NumberField title="Annual return %" value={rate} set={setRate}/><NumberField title="Years" value={years} set={setYears}/><NumberField title="Monthly contribution" value={monthly} set={setMonthly}/></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><ResultCard title="Future value" value={`$${future.toFixed(2)}`}/><ResultCard title="Contributions" value={`$${contributed.toFixed(2)}`}/><ResultCard title="Estimated growth" value={`$${(future-contributed).toFixed(2)}`}/></div></div>}

function NumberField({title,value,set}:{title:string,value:number,set:(v:number)=>void}){return <div><label className={label}>{title}</label><input type="number" className={input} value={value} onChange={e=>set(Number(e.target.value))}/></div>}
function ResultCard({title,value}:{title:string,value:string}){return <div className="rounded-2xl bg-[#F7F0E9] p-5"><div className="text-sm font-bold text-[#6B5B4D]">{title}</div><div className="mt-2 text-2xl font-black text-[#A7744D]">{value}</div></div>}

export function DateDifferenceTool(){const [start,setStart]=useState("");const [end,setEnd]=useState("");const result=useMemo(()=>{const a=new Date(start),b=new Date(end);if(!start||!end||Number.isNaN(a.getTime())||Number.isNaN(b.getTime()))return null;const days=Math.abs(Math.round((b.getTime()-a.getTime())/86400000));return {days,weeks:(days/7).toFixed(2),months:(days/30.4375).toFixed(2)}},[start,end]);return <div className={panel}><div className="grid gap-5 sm:grid-cols-2"><div><label className={label}>Start date</label><input type="date" className={input} value={start} onChange={e=>setStart(e.target.value)}/></div><div><label className={label}>End date</label><input type="date" className={input} value={end} onChange={e=>setEnd(e.target.value)}/></div></div>{result&&<div className="mt-6 grid gap-4 sm:grid-cols-3"><ResultCard title="Days" value={String(result.days)}/><ResultCard title="Weeks" value={result.weeks}/><ResultCard title="Approx. months" value={result.months}/></div>}</div>}

const conversions={Length:{Meter:1,Kilometer:1000,Centimeter:.01,Millimeter:.001,Mile:1609.344,Yard:.9144,Foot:.3048,Inch:.0254},Weight:{Kilogram:1,Gram:.001,Pound:.45359237,Ounce:.0283495},Temperature:{Celsius:1,Fahrenheit:1,Kelvin:1}} as const;
export function UnitConverterTool(){const [kind,setKind]=useState<keyof typeof conversions>("Length");const names=Object.keys(conversions[kind]);const [from,setFrom]=useState("Meter");const [to,setTo]=useState("Kilometer");const [value,setValue]=useState(1);const changeKind=(k:keyof typeof conversions)=>{setKind(k);const n=Object.keys(conversions[k]);setFrom(n[0]);setTo(n[1])};const result=useMemo(()=>{if(kind==="Temperature"){let c=value;if(from==="Fahrenheit")c=(value-32)*5/9;if(from==="Kelvin")c=value-273.15;return to==="Celsius"?c:to==="Fahrenheit"?c*9/5+32:c+273.15}const map=conversions[kind] as Record<string,number>;return value*map[from]/map[to]},[kind,from,to,value]);return <div className={panel}><div className="grid gap-4 sm:grid-cols-4"><div><label className={label}>Type</label><select className={input} value={kind} onChange={e=>changeKind(e.target.value as keyof typeof conversions)}>{Object.keys(conversions).map(k=><option key={k}>{k}</option>)}</select></div><NumberField title="Value" value={value} set={setValue}/><div><label className={label}>From</label><select className={input} value={from} onChange={e=>setFrom(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select></div><div><label className={label}>To</label><select className={input} value={to} onChange={e=>setTo(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select></div></div><div className="mt-6 rounded-3xl bg-[#F7F0E9] p-8 text-center text-4xl font-black text-[#A7744D]">{Number.isFinite(result)?result.toLocaleString(undefined,{maximumFractionDigits:8}):"—"}</div></div>}

export function ColorConverterTool(){const [hex,setHex]=useState("#A7744D");const valid=/^#?[0-9a-f]{6}$/i.test(hex);const normalized=hex.startsWith("#")?hex:`#${hex}`;const rgb=valid?{r:parseInt(normalized.slice(1,3),16),g:parseInt(normalized.slice(3,5),16),b:parseInt(normalized.slice(5,7),16)}:null;return <div className={panel}><div className="grid gap-5 sm:grid-cols-[160px_1fr]"><input type="color" value={valid?normalized:"#A7744D"} onChange={e=>setHex(e.target.value)} className="h-24 w-full rounded-2xl border border-[#E7D8C7] bg-white p-2"/><div><label className={label}>HEX color</label><input className={input} value={hex} onChange={e=>setHex(e.target.value)}/>{rgb&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><ResultCard title="RGB" value={`rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`}/><ResultCard title="CSS HEX" value={normalized.toUpperCase()}/></div>}</div></div></div>}
