"use client";

import { useState } from "react";

const panel = "rounded-3xl border border-[#E7D8C7] bg-[#FFFCF8] p-6 shadow-[0_16px_45px_rgba(91,62,38,.08)] sm:p-8";
const input = "w-full rounded-2xl border border-[#E7D8C7] bg-white px-4 py-3 text-[#2D241C] outline-none transition focus:border-[#A7744D] focus:ring-4 focus:ring-[#A7744D]/10";
const button = "rounded-2xl bg-[#A7744D] px-5 py-3 font-bold text-white transition hover:bg-[#8F603D] disabled:cursor-not-allowed disabled:opacity-50";
const label = "mb-2 block text-sm font-bold text-[#4A3A2E]";

function download(bytes: Uint8Array, name: string) {
  const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = name; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function Picker({ onFile, text="Choose or drop a PDF" }: { onFile: (file: File | null) => void; text?: string }) {
  return <label className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-3xl border-2 border-dashed border-[#D9C4AE] bg-[#FFF9F2] px-6 text-center transition hover:border-[#A7744D] hover:bg-[#F8EDE1]"><span className="text-lg font-black text-[#2D241C]">{text}</span><span className="mt-2 text-sm text-[#6B5B4D]">Processing stays in your browser.</span><input className="hidden" type="file" accept="application/pdf" onChange={e=>onFile(e.target.files?.[0]||null)}/></label>;
}
function Status({files,error}:{files:(File|null)[];error:string}){return <>{files.filter(Boolean).map((f,i)=><p key={i} className="mt-3 font-bold text-[#4A3A2E]">{f!.name}</p>)}{error&&<p className="mt-4 rounded-2xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}</>}
function parsePages(text:string,count:number){const out:number[]=[];for(const raw of text.split(",")){const p=raw.trim();if(!p)continue;if(p.includes("-")){const[a,b]=p.split("-").map(Number);if(!Number.isInteger(a)||!Number.isInteger(b))throw new Error(`Invalid range: ${p}`);const s=a<=b?1:-1;for(let n=a;s>0?n<=b:n>=b;n+=s){if(n<1||n>count)throw new Error(`Page ${n} is outside this PDF.`);out.push(n-1)}}else{const n=Number(p);if(!Number.isInteger(n)||n<1||n>count)throw new Error(`Invalid page: ${p}`);out.push(n-1)}}if(!out.length)throw new Error("Enter at least one page.");return out}

export function PdfSplitEveryNTool(){const[file,setFile]=useState<File|null>(null),[n,setN]=useState(2),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{if(!Number.isInteger(n)||n<1)throw new Error("Pages per PDF must be at least 1.");const{PDFDocument}=await import("pdf-lib");const src=await PDFDocument.load(await file.arrayBuffer());for(let start=0,part=1;start<src.getPageCount();start+=n,part++){const out=await PDFDocument.create();(await out.copyPages(src,Array.from({length:Math.min(n,src.getPageCount()-start)},(_,i)=>start+i))).forEach(p=>out.addPage(p));download(await out.save(),`split-part-${part}.pdf`);await new Promise(r=>setTimeout(r,120))}}catch(e){setError(e instanceof Error?e.message:"Could not split this PDF.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><label className={`${label} mt-5`}>Pages per output PDF</label><input className={input} type="number" min="1" value={n} onChange={e=>setN(Number(e.target.value))}/><p className="mt-2 text-sm text-[#6B5B4D]">Your browser downloads one PDF for each chunk.</p><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Splitting…":"Split every N pages"}</button></div>}

export function PdfRotateSelectedTool(){const[file,setFile]=useState<File|null>(null),[pages,setPages]=useState("1"),[angle,setAngle]=useState(90),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{const{PDFDocument,degrees}=await import("pdf-lib");const pdf=await PDFDocument.load(await file.arrayBuffer());const ids=[...new Set(parsePages(pages,pdf.getPageCount()))];ids.forEach(i=>{const p=pdf.getPage(i);p.setRotation(degrees((p.getRotation().angle+angle)%360))});download(await pdf.save(),"selected-pages-rotated.pdf")}catch(e){setError(e instanceof Error?e.message:"Could not rotate pages.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className={label}>Pages</label><input className={input} value={pages} onChange={e=>setPages(e.target.value)} placeholder="1,3-5"/></div><div><label className={label}>Rotation</label><select className={input} value={angle} onChange={e=>setAngle(Number(e.target.value))}><option value={90}>90° clockwise</option><option value={180}>180°</option><option value={270}>90° counter-clockwise</option></select></div></div><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Rotating…":"Rotate selected pages"}</button></div>}

export function PdfInsertTool(){const[base,setBase]=useState<File|null>(null),[insert,setInsert]=useState<File|null>(null),[after,setAfter]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!base||!insert)return;setBusy(true);setError("");try{const{PDFDocument}=await import("pdf-lib");const a=await PDFDocument.load(await base.arrayBuffer()),b=await PDFDocument.load(await insert.arrayBuffer());if(after<0||after>a.getPageCount())throw new Error(`Position must be from 0 to ${a.getPageCount()}.`);const out=await PDFDocument.create();const first=await out.copyPages(a,Array.from({length:after},(_,i)=>i));first.forEach(p=>out.addPage(p));(await out.copyPages(b,b.getPageIndices())).forEach(p=>out.addPage(p));(await out.copyPages(a,Array.from({length:a.getPageCount()-after},(_,i)=>after+i))).forEach(p=>out.addPage(p));download(await out.save(),"pdf-inserted.pdf")}catch(e){setError(e instanceof Error?e.message:"Could not insert this PDF.")}finally{setBusy(false)}}return <div className={panel}><div className="grid gap-4 sm:grid-cols-2"><Picker text="Choose main PDF" onFile={setBase}/><Picker text="Choose PDF to insert" onFile={setInsert}/></div><Status files={[base,insert]} error={error}/><label className={`${label} mt-5`}>Insert after page (0 = beginning)</label><input className={input} type="number" min="0" value={after} onChange={e=>setAfter(Number(e.target.value))}/><button className={`${button} mt-5`} disabled={!base||!insert||busy} onClick={run}>{busy?"Inserting…":"Insert PDF"}</button></div>}

export function PdfSwapPagesTool(){const[file,setFile]=useState<File|null>(null),[a,setA]=useState(1),[b,setB]=useState(2),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{const{PDFDocument}=await import("pdf-lib");const src=await PDFDocument.load(await file.arrayBuffer()),n=src.getPageCount();if(a<1||b<1||a>n||b>n||a===b)throw new Error(`Choose two different pages between 1 and ${n}.`);const order=src.getPageIndices();[order[a-1],order[b-1]]=[order[b-1],order[a-1]];const out=await PDFDocument.create();(await out.copyPages(src,order)).forEach(p=>out.addPage(p));download(await out.save(),"pages-swapped.pdf")}catch(e){setError(e instanceof Error?e.message:"Could not swap pages.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className={label}>First page</label><input className={input} type="number" min="1" value={a} onChange={e=>setA(Number(e.target.value))}/></div><div><label className={label}>Second page</label><input className={input} type="number" min="1" value={b} onChange={e=>setB(Number(e.target.value))}/></div></div><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Swapping…":"Swap pages"}</button></div>}

export function PdfNormalizeSizesTool(){const[file,setFile]=useState<File|null>(null),[mode,setMode]=useState("first"),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{const{PDFDocument}=await import("pdf-lib");const src=await PDFDocument.load(await file.arrayBuffer());const sizes=src.getPages().map(p=>p.getSize());let target=sizes[0];if(mode==="largest")target=sizes.reduce((x,y)=>x.width*x.height>=y.width*y.height?x:y);if(mode==="a4")target={width:595.28,height:841.89};const out=await PDFDocument.create();for(const p of src.getPages()){const s=p.getSize(),scale=Math.min(target.width/s.width,target.height/s.height),w=s.width*scale,h=s.height*scale,page=out.addPage([target.width,target.height]),[emb]=await out.embedPages([p]);page.drawPage(emb,{x:(target.width-w)/2,y:(target.height-h)/2,width:w,height:h})}download(await out.save(),"normalized-page-sizes.pdf")}catch(e){setError(e instanceof Error?e.message:"Could not normalize pages.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><label className={`${label} mt-5`}>Target page size</label><select className={input} value={mode} onChange={e=>setMode(e.target.value)}><option value="first">Match first page</option><option value="largest">Match largest page</option><option value="a4">A4 portrait</option></select><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Normalizing…":"Normalize page sizes"}</button></div>}

export function PdfAddMarginsTool(){const[file,setFile]=useState<File|null>(null),[margin,setMargin]=useState(36),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{if(margin<0||margin>300)throw new Error("Margin must be between 0 and 300 points.");const{PDFDocument}=await import("pdf-lib");const src=await PDFDocument.load(await file.arrayBuffer()),out=await PDFDocument.create();for(const p of src.getPages()){const s=p.getSize(),page=out.addPage([s.width+margin*2,s.height+margin*2]),[emb]=await out.embedPages([p]);page.drawPage(emb,{x:margin,y:margin,width:s.width,height:s.height})}download(await out.save(),"pdf-with-margins.pdf")}catch(e){setError(e instanceof Error?e.message:"Could not add margins.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><label className={`${label} mt-5`}>Margin in PDF points (72 = 1 inch)</label><input className={input} type="number" min="0" max="300" value={margin} onChange={e=>setMargin(Number(e.target.value))}/><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Adding…":"Add margins"}</button></div>}

function OrientationTool({landscape}:{landscape:boolean}){const[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{const{PDFDocument}=await import("pdf-lib");const src=await PDFDocument.load(await file.arrayBuffer());const ids=src.getPageIndices().filter(i=>{const s=src.getPage(i).getSize();return landscape?s.width>s.height:s.height>=s.width});if(!ids.length)throw new Error(`No ${landscape?"landscape":"portrait"} pages found.`);const out=await PDFDocument.create();(await out.copyPages(src,ids)).forEach(p=>out.addPage(p));download(await out.save(),`${landscape?"landscape":"portrait"}-pages.pdf`)}catch(e){setError(e instanceof Error?e.message:"Could not extract pages.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Extracting…":`Extract ${landscape?"landscape":"portrait"} pages`}</button></div>}
export function PdfLandscapePagesTool(){return <OrientationTool landscape/>} export function PdfPortraitPagesTool(){return <OrientationTool landscape={false}/>}

export function PdfExtractEndsTool(){const[file,setFile]=useState<File|null>(null),[mode,setMode]=useState("both"),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{const{PDFDocument}=await import("pdf-lib");const src=await PDFDocument.load(await file.arrayBuffer()),n=src.getPageCount();const ids=mode==="first"?[0]:mode==="last"?[n-1]:n===1?[0]:[0,n-1];const out=await PDFDocument.create();(await out.copyPages(src,ids)).forEach(p=>out.addPage(p));download(await out.save(),"first-last-pages.pdf")}catch(e){setError(e instanceof Error?e.message:"Could not extract pages.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><label className={`${label} mt-5`}>Pages to extract</label><select className={input} value={mode} onChange={e=>setMode(e.target.value)}><option value="both">First and last</option><option value="first">First only</option><option value="last">Last only</option></select><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Extracting…":"Extract end pages"}</button></div>}

export function PdfRemoveEndsTool(){const[file,setFile]=useState<File|null>(null),[first,setFirst]=useState(true),[last,setLast]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{const{PDFDocument}=await import("pdf-lib");const pdf=await PDFDocument.load(await file.arrayBuffer());if(!first&&!last)throw new Error("Choose at least one page to remove.");if(pdf.getPageCount()-(first?1:0)-(last?1:0)<1)throw new Error("The PDF must keep at least one page.");if(last)pdf.removePage(pdf.getPageCount()-1);if(first)pdf.removePage(0);download(await pdf.save(),"end-pages-removed.pdf")}catch(e){setError(e instanceof Error?e.message:"Could not remove pages.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><div className="mt-5 flex flex-wrap gap-5"><label className="font-bold text-[#4A3A2E]"><input className="mr-2 accent-[#A7744D]" type="checkbox" checked={first} onChange={e=>setFirst(e.target.checked)}/>Remove first page</label><label className="font-bold text-[#4A3A2E]"><input className="mr-2 accent-[#A7744D]" type="checkbox" checked={last} onChange={e=>setLast(e.target.checked)}/>Remove last page</label></div><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Removing…":"Remove end pages"}</button></div>}

export function PdfRepeatDocumentTool(){const[file,setFile]=useState<File|null>(null),[copies,setCopies]=useState(2),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{if(!Number.isInteger(copies)||copies<2||copies>20)throw new Error("Copies must be between 2 and 20.");const{PDFDocument}=await import("pdf-lib");const src=await PDFDocument.load(await file.arrayBuffer()),out=await PDFDocument.create();for(let c=0;c<copies;c++)(await out.copyPages(src,src.getPageIndices())).forEach(p=>out.addPage(p));download(await out.save(),"repeated-document.pdf")}catch(e){setError(e instanceof Error?e.message:"Could not repeat this PDF.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><label className={`${label} mt-5`}>Total copies</label><input className={input} type="number" min="2" max="20" value={copies} onChange={e=>setCopies(Number(e.target.value))}/><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Repeating…":"Repeat entire PDF"}</button></div>}

export function PdfExtractRangeTool(){const[file,setFile]=useState<File|null>(null),[start,setStart]=useState(1),[end,setEnd]=useState(3),[busy,setBusy]=useState(false),[error,setError]=useState("");async function run(){if(!file)return;setBusy(true);setError("");try{const{PDFDocument}=await import("pdf-lib");const src=await PDFDocument.load(await file.arrayBuffer()),n=src.getPageCount();if(start<1||end<start||end>n)throw new Error(`Use a valid range between 1 and ${n}.`);const out=await PDFDocument.create();(await out.copyPages(src,Array.from({length:end-start+1},(_,i)=>start-1+i))).forEach(p=>out.addPage(p));download(await out.save(),`pages-${start}-${end}.pdf`)}catch(e){setError(e instanceof Error?e.message:"Could not extract this range.")}finally{setBusy(false)}}return <div className={panel}><Picker onFile={setFile}/><Status files={[file]} error={error}/><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className={label}>Start page</label><input className={input} type="number" min="1" value={start} onChange={e=>setStart(Number(e.target.value))}/></div><div><label className={label}>End page</label><input className={input} type="number" min="1" value={end} onChange={e=>setEnd(Number(e.target.value))}/></div></div><button className={`${button} mt-5`} disabled={!file||busy} onClick={run}>{busy?"Extracting…":"Extract page range"}</button></div>}
